import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAF7',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 15,
    color: '#999',
    lineHeight: 22,
  },
  voiceCard: {
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
    padding: 16,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  voiceIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#C8E6C9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  voiceContent: {
    flex: 1,
  },
  voiceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  voiceTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginRight: 8,
  },
  easyBadge: {
    backgroundColor: '#4CAF50',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  easyText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#FFF',
  },
  voiceDescription: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  required: {
    color: '#E8505B',
  },
  inputContainer: {
    marginBottom: 20,
  },
  input: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 10,
    padding: 16,
    fontSize: 15,
    color: '#333',
  },
  inputWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 10,
    paddingRight: 12,
  },
  inputFlex: {
    flex: 1,
    padding: 16,
    fontSize: 15,
    color: '#333',
  },
  micButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFE5E5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  tip: {
    fontSize: 12,
    color: '#BBB',
    marginTop: 6,
    fontStyle: 'italic',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  infoIcon: {
    marginRight: 6,
  },
  infoText: {
    fontSize: 12,
    color: '#4CAF50',
    flex: 1,
  },
  stepsContainer: {
    marginBottom: 20,
  },
  stepItem: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
  },
  stepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  stepNumber: {
    fontSize: 15,
    fontWeight: '600',
    color: '#E8505B',
  },
  removeButton: {
    padding: 4,
  },
  stepInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  stepInput: {
    flex: 1,
    fontSize: 15,
    color: '#333',
    padding: 0,
  },
  addStepButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: '#E8505B',
    borderStyle: 'dashed',
    borderRadius: 10,
    padding: 16,
    marginBottom: 24,
  },
  addStepText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#E8505B',
    marginLeft: 8,
  },
  creditCard: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  creditLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  creditIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF3E0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  creditContent: {
    flex: 1,
  },
  creditTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  creditDescription: {
    fontSize: 13,
    color: '#999',
  },
  displayInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 8,
    padding: 12,
    marginBottom: 24,
  },
  displayText: {
    fontSize: 13,
    color: '#666',
    marginLeft: 8,
  },
  displayName: {
    fontWeight: '600',
    color: '#333',
  },
  saveButton: {
    backgroundColor: '#E8505B',
    borderRadius: 30,
    padding: 18,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 12,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: '#FAFAF7',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 8,
  },
  saveNote: {
    fontSize: 12,
    color: '#BBB',
    textAlign: 'center',
    lineHeight: 18,
  },
  categorySelector: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 10,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryPlaceholderText: {
    fontSize: 15,
    color: '#CCC',
  },
  categorySelectedText: {
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },
  categoryOptions: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 10,
    marginTop: 8,
    overflow: 'hidden',
  },
  categoryOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  categoryOptionSelected: {
    backgroundColor: '#FFF5F5',
  },
  categoryOptionText: {
    fontSize: 15,
    color: '#333',
  },
  categoryOptionTextSelected: {
    fontSize: 15,
    color: '#E8505B',
    fontWeight: '600',
  },
  imagePickerButton: {
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: '#E5E5E5',
    borderStyle: 'dashed',
    borderRadius: 10,
    overflow: 'hidden',
    minHeight: 200,
  },
  imagePickerPlaceholder: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FAFAF7',
  },
  imagePickerText: {
    marginTop: 12,
    fontSize: 15,
    color: '#999',
    fontWeight: '500',
  },
  selectedImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  removeImageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    padding: 8,
  },
  removeImageText: {
    fontSize: 14,
    color: '#FF5252',
    marginLeft: 6,
    fontWeight: '500',
  },
});
